name: Remote Dispatch Action Initiator

on:
    push:
        branches:
            - 'preview'

jobs:
    trigger_preview_build:
        name: Trigger preview build
        runs-on: ubuntu-latest

        steps:
            - name: Checkout sources
              uses: actions/checkout@v6

            - name: Create Tag
              run: |
                  git tag "preview-${{ github.run_number }}"
                  git push origin "preview-${{ github.run_number }}"

            - name: Dispatch preview build event
              run: |
                  curl -fsSL -X POST https://api.github.com/repos/jobobby04/TachiyomiSYPreview/dispatches \
                  -H 'Accept: application/vnd.github+json' \
                  -H 'X-GitHub-Api-Version: 2022-11-28' \
                  -H 'Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}' \
                  --data '{"event_type": "ping", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
